gitui-org/gitui

- src/components/help.rs
- src/main.rs
- src/version.rs
> show version in help popup

- .github/workflows/ci.yml
- CHANGELOG.md
- Makefile
- asyncgit/src/sync/tags.rs
- src/tabs/revlog/mod.rs
> support multiple tags per commit

- Cargo.lock
- Cargo.toml
- src/main.rs
It uses `clap` crate to do it.
closes #88
> replaces GITUI_LOGGING env variable by `-l` or `--gitui-logging`

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/cmdbar.rs
- src/keys.rs
- src/main.rs
- src/strings.rs
- src/ui/style.rs
> Support more commands

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- Makefile
- README.md
- asyncgit/src/commit_files.rs
- asyncgit/src/lib.rs
- asyncgit/src/revlog.rs
- asyncgit/src/sync/commit_details.rs
- asyncgit/src/sync/commit_files.rs
- asyncgit/src/sync/commits_info.rs
- asyncgit/src/sync/mod.rs
- asyncgit/src/sync/status.rs
- src/app.rs
- src/components/changes.rs
- src/components/commit_details.rs
- src/components/commitlist.rs
- src/components/filetree.rs
- src/components/help.rs
- src/components/mod.rs
- src/components/utils/filetree.rs
- src/components/utils/logitems.rs
- src/components/utils/mod.rs
- src/components/utils/statustree.rs
- src/keys.rs
- src/strings.rs
- src/tabs/revlog.rs
> commit details in log

- src/components/mod.rs
> wrap TextInputComponent text

- src/components/textinput.rs
> use is_char_boundary() to simplify logic

- CHANGELOG.md
- asyncgit/src/sync/diff.rs
- asyncgit/src/sync/hunks.rs
- asyncgit/src/sync/mod.rs
- asyncgit/src/sync/reset.rs
- asyncgit/src/sync/utils.rs
- src/app.rs
- src/components/diff.rs
- src/components/reset.rs
- src/keys.rs
- src/queue.rs
- src/strings.rs
> Reset hunk #11

- README.md
GitUI got successfully submitted to the official Homebrew repo. 🎉 
https://formulae.brew.sh/formula/gitui#default
> Use official Homebrew formula

- .github/workflows/ci.yml
> fix windows ci

- README.md
Fixing a copy-paste error / typo ;-)
> Correct branching issue #

- src/components/filetree.rs
Closes #295 
Fixes scrolling in filetrees
> Fix scrolling in filetrees

- README.md
It would be awesome if [git-brunch](https://github.com/andys8/git-brunch) would be listed as one of the inspirations for the new branch functionality. Only if that's fine for you @extrawurst of course :) 
<https://twitter.com/Extrawurst/status/1301590345231273984>
> Readme inspiration list: git-brunch

- CHANGELOG.md
Just fixes the link in the changelog
> Fix WizardOhio24 link in changelog

- src/tabs/status.rs
> Remove Checkout Branch from tabs in which it cannot be activated

- src/components/push.rs
> fix: gauge style

- src/strings.rs
- src/tabs/revlog.rs
> feat: add branch selection popup in the log view

- src/cmdbar.rs
- src/components/help.rs
- src/components/select_branch.rs
- src/ui/mod.rs
> fix branch list and cmd bar panicing on small terminal sizes

- .github/workflows/ci.yml
- Makefile
> Windows MSI - add display of file size

- asyncgit/src/sync/hooks.rs
> fix hook panicking

- .github/workflows/ci.yml
An attempt to get MacOS to work with the Github Actions CI caching
> MacOS github CI workaround

- asyncgit/src/sync/remotes.rs
Let's keep things gender neutral :)
> Change he and his to they and their in comment

- src/components/commitlist.rs
- src/strings.rs
- src/tabs/revlog.rs
> copy commit hash

- asyncgit/src/sync/branch.rs
- src/tabs/status.rs
> show branch ahead/behind only if upstream is set

- asyncgit/src/sync/branch.rs
- asyncgit/src/sync/remotes.rs
- src/tabs/status.rs
> Set tracking branch on push

- CHANGELOG.md
- Cargo.toml
- src/clipboard.rs
> Freebsd fix compilation

- src/components/textinput.rs
> Small spelling fix: Change test_invisable_newline to test_invisible_newline

- asyncgit/src/sync/logwalker.rs
- asyncgit/src/sync/remotes.rs
Fixes CI which is failing on nightly due to clippy
> Fix nightly clippy problems

- asyncgit/src/sync/remotes.rs
> actually commit the temp files for flaky/failing unittest

- CHANGELOG.md
- src/components/select_branch.rs
> fix missing paging support in branch list

- CHANGELOG.md
- src/components/inspect_commit.rs
> support left arrow to go back grom commit details

- asyncgit/src/sync/state.rs
- src/tabs/status.rs
> only show non-clean repo states

- src/components/pull.rs
> only even try to ff merge when there is something incoming

- asyncgit/src/fetch.rs
- asyncgit/src/push.rs
- asyncgit/src/remote_progress.rs
- src/components/push.rs
- src/strings.rs
> fix fetch notifications

- asyncgit/src/sync/branch/merge_commit.rs
- asyncgit/src/sync/branch/merge_ff.rs
- asyncgit/src/sync/branch/mod.rs
- asyncgit/src/sync/commit.rs
- asyncgit/src/sync/mod.rs
- src/components/pull.rs
> support conflict-free merge-commit

- src/tabs/status.rs
> refresh compare state at the right time

- CHANGELOG.md
- asyncgit/src/sync/branch/merge_commit.rs
- src/app.rs
- src/components/pull.rs
- src/components/reset.rs
- src/queue.rs
- src/strings.rs
> user confirm merge

- CHANGELOG.md
- src/components/diff.rs
> Fix 583 fix diff line selection

- CHANGELOG.md
- src/components/cred.rs
- src/components/pull.rs
- src/components/push.rs
- src/components/push_tags.rs
> Fix 586 deadlock pull creds

- CHANGELOG.md
- asyncgit/src/sync/branch/mod.rs
- asyncgit/src/sync/mod.rs
- src/components/push.rs
> Use upstream remote

- Cargo.lock
- Cargo.toml
- src/components/branchlist.rs
> branchlist was ignoring unicode boundaries on truncating strings

- asyncgit/src/sync/staging/mod.rs
- asyncgit/src/sync/staging/stage_tracked.rs
> fix panic on staging lines involving missing newline eof

- src/components/branchlist.rs
> fix branchname width misalignment

- CHANGELOG.md
- src/components/branchlist.rs
> fix empty branch list enter key still accepted and panics

- src/components/blame_file.rs
This addresses the 4 remaining comments in #634.
> Address minor issues in blame view

- CHANGELOG.md
- asyncgit/src/sync/commits_info.rs
> limit log message to first line of commit msg

- asyncgit/src/sync/blame.rs
This results in far fewer calls to `repo.find_commit` in almost all
cases.
This is a follow-up to #634.
> Call get_commits_info instead of get_commit_info

- asyncgit/src/sync/diff.rs
- asyncgit/src/sync/staging/mod.rs
The DiffLineType enum in asyncgit has fewer variants: it maps context lines and
line types we don't expect to None. This behavior is kept unchanged.
Now calls `.origin_value()` rather than `.origin()` except in one debug log.
closes #655
> Use git2::DiffLineType enum instead of char values (#655)

- src/app.rs
- src/components/blame_file.rs
- src/components/branchlist.rs
- src/components/changes.rs
- src/components/commit.rs
- src/components/commit_details/details.rs
- src/components/commit_details/mod.rs
- src/components/commitlist.rs
- src/components/create_branch.rs
- src/components/cred.rs
- src/components/diff.rs
- src/components/externaleditor.rs
- src/components/filetree.rs
- src/components/help.rs
- src/components/inspect_commit.rs
- src/components/mod.rs
- src/components/msg.rs
- src/components/pull.rs
- src/components/push.rs
- src/components/push_tags.rs
- src/components/rename_branch.rs
- src/components/reset.rs
- src/components/stashmsg.rs
- src/components/tag_commit.rs
- src/components/textinput.rs
- src/tabs/revlog.rs
- src/tabs/stashing.rs
- src/tabs/stashlist.rs
- src/tabs/status.rs
> introduce EventState enum

- Cargo.lock
- Cargo.toml
- src/components/branchlist.rs
- src/components/diff.rs
- src/ui/scrollbar.rs
> fix branchlist scrollbr

- CHANGELOG.md
- src/components/commitlist.rs
- src/components/utils/logitems.rs
> Fix 682 smarter times in log

- src/input.rs
> allow input error to be logged and abort program

- asyncgit/src/sync/branch/merge_commit.rs
- asyncgit/src/sync/merge.rs
- asyncgit/src/sync/mod.rs
- src/components/commit.rs
- src/strings.rs
> Commit merge

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/bug_report.rs
- src/main.rs
> Zcorniere master

- src/app.rs
- src/components/changes.rs
- src/queue.rs
- src/tabs/status.rs
> move focus after last file staged

- asyncgit/src/sync/tree.rs
- src/components/revision_files.rs
- src/ui/mod.rs
- src/ui/scrolllist.rs
> treeview shows selectd file content

- Cargo.lock
- Cargo.toml
- Makefile
- async_utils/Cargo.toml
- async_utils/LICENSE.md
- async_utils/src/lib.rs
- asyncgit/src/lib.rs
- src/app.rs
- src/components/revision_files.rs
- src/ui/mod.rs
- src/ui/syntax_text.rs
> add syntax highlighting

- Cargo.lock
> git2-rs update

- CHANGELOG.md
- src/components/revision_files.rs
> fix wrong file loaded in tree view

- asyncgit/src/sync/merge.rs
Solves #751.
First time contributing, let me know if I did something terribly wrong.
> Use libgit2 to get the merge commit message.

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Makefile
- asyncgit/Cargo.toml
> fix openssl vendoring with new resolver

- CHANGELOG.md
- asyncgit/src/sync/tree.rs
- filetreelist/src/filetree.rs
> filetree paniced on non utf8 files/paths

- asyncgit/src/lib.rs
- src/app.rs
- src/components/revision_files.rs
- src/components/revision_files_popup.rs
- src/components/syntax_text.rs
- src/components/taglist.rs
- src/main.rs
- src/tabs/files.rs
> app has its own async notifications now

- THEMES.md
Thats where it is on my mac. (And on [other peoples mac](https://github.com/extrawurst/gitui/issues/799#issue-933238213))
> Fix the path of the theme file on mac

- CHANGELOG.md
- asyncgit/src/sync/ignore.rs
> do not allow to ignore gitignore

- CHANGELOG.md
- asyncgit/src/sync/commit_files.rs
> get_commit_diff on commit with unknown parent

- asyncgit/Cargo.toml
- asyncgit/src/lib.rs
- src/main.rs
> hook into libgit2 tracing

- src/components/blame_file.rs
> workaround tui-rs issue

- CHANGELOG.md
- asyncgit/src/tags.rs
> fix tags being fetched every scroll in revlog

- src/app.rs
- src/input.rs
> dont use process::abort on input thread error

- src/components/commitlist.rs
This PR visualises the scrollbar position in the revlog. 
Closes #868.
---
Checklist:
> Add scrollbar to revlog

- Cargo.lock
> bump git2rs

- .github/workflows/ci.yml
temporarily disable sec audit ci to finally get green CI again
see #950, #951
> disable sec audit temporarily

- .cargo/audit.toml
- .github/workflows/ci.yml
> bring back audit to CI

- CHANGELOG.md
- asyncgit/src/sync/remotes/mod.rs
- asyncgit/src/sync/remotes/tags.rs
> pull gets tags on current branch

- CHANGELOG.md
- Cargo.lock
> git2rs upgrade

- CHANGELOG.md
- src/components/revision_files.rs
> allow opening file selected in tree

- asyncgit/src/sync/hooks.rs
> use .git path instead of workdir finding hooks

- .github/workflows/ci.yml
- asyncgit/src/sync/hooks.rs
> run hooks in correct pwd (#1046)

- CHANGELOG.md
- README.md
- asyncgit/src/sync/commit.rs
- asyncgit/src/sync/commit_revert.rs
- asyncgit/src/sync/merge.rs
- asyncgit/src/sync/mod.rs
- asyncgit/src/sync/state.rs
- asyncgit/src/sync/utils.rs
- src/app.rs
- src/components/branchlist.rs
- src/components/commit.rs
- src/components/reset.rs
- src/components/revision_files.rs
- src/queue.rs
- src/strings.rs
- src/tabs/revlog.rs
- src/tabs/stashlist.rs
- src/tabs/status.rs
> implement reverting commit from revlog

- CHANGELOG.md
- src/tabs/status.rs
> do not allow pull on local-only branch

- CHANGELOG.md
- asyncgit/src/lib.rs
- asyncgit/src/push.rs
- asyncgit/src/sync/branch/merge_commit.rs
- asyncgit/src/sync/branch/merge_ff.rs
- asyncgit/src/sync/branch/merge_rebase.rs
- asyncgit/src/sync/branch/mod.rs
- asyncgit/src/sync/mod.rs
- asyncgit/src/sync/remotes/mod.rs
- asyncgit/src/sync/remotes/push.rs
- asyncgit/src/sync/remotes/tags.rs
- src/app.rs
- src/components/push.rs
- src/components/reset.rs
- src/queue.rs
- src/strings.rs
- src/tabs/status.rs
> support deleting tag on remote

- asyncgit/src/sync/tags.rs
- src/app.rs
- src/components/msg.rs
- src/components/taglist.rs
- src/queue.rs
- src/strings.rs
> allow inspecting tag annotation

- CHANGELOG.md
- src/tabs/status.rs
> Fix 1102 performance reg

- asyncgit/src/sync/remotes/mod.rs
- asyncgit/src/sync/remotes/push.rs
- asyncgit/src/sync/remotes/tags.rs
> use auto proxy option

- src/app.rs
- src/tabs/status.rs
> Fix 1104 performance regression

- CHANGELOG.md
- src/components/taglist.rs
> fix issue with taglist component without remotes

- CHANGELOG.md
- asyncgit/src/sync/mod.rs
- asyncgit/src/sync/status.rs
- src/components/changes.rs
> switch focus to index after staging last file

- CHANGELOG.md
This Pull Request fixes/closes 846.
- Fix URL to issue 846
> Changelog: Fix URL to issue 846

- CHANGELOG.md
- src/app.rs
- src/components/commitlist.rs
- src/tabs/stashlist.rs
fix for bug discovered and described in https://github.com/extrawurst/gitui/pull/1201
> Fix stashlist after marked drop

- Cargo.lock
This Pull Request fixes/closes #{issue_num}.
-
-
> update chrono dependency

- CHANGELOG.md
- Cargo.toml
- src/clipboard.rs
This Pull Request fixes/closes #397.
- support copy to clipboard on wayland
> support copy to clipboard on wayland

- Cargo.lock
- README.md
- asyncgit/Cargo.toml
- asyncgit/src/error.rs
- asyncgit/src/sync/mod.rs
- asyncgit/src/sync/repository.rs
- asyncgit/src/sync/submodules.rs
- src/app.rs
- src/components/submodules.rs
- src/input.rs
- src/keys/key_config.rs
- src/keys/key_list.rs
- src/keys/key_list_file.rs
- src/keys/symbols.rs
- src/main.rs
- src/queue.rs
- src/strings.rs
- src/ui/style.rs
This will allow opening a submodule in gitui.
> prepare for opening submodule

- src/main.rs
This Pull Request fixes/closes #{issue_num}.
-  Adds log_eprintlin! macro to address TODO in main.rs
> Addresses TODO with macro log_eprintln!

- Cargo.lock
- asyncgit/Cargo.toml
- asyncgit/src/sync/config.rs
- asyncgit/src/sync/diff.rs
- src/components/changes.rs
- src/components/options_popup.rs
- src/options.rs
- src/tabs/status.rs
> Persist all options 1340

- CHANGELOG.md
- src/app.rs
- src/components/commit.rs
- src/keys/key_list.rs
- src/keys/key_list_file.rs
- src/options.rs
- src/strings.rs
> Commit msg history

- Makefile
This Pull Request fixes/closes https://github.com/extrawurst/gitui/issues/1392 .
- add clean to make file
- thats it
> make: add clean cmd

- THEMES.md
- add link to themes.md for convenience
> Add link from themes.md to referenced code block

- CHANGELOG.md
- src/components/inspect_commit.rs
- src/components/status_tree.rs
> Edit file from file tree

- CHANGELOG.md
- asyncgit/src/lib.rs
- asyncgit/src/treefiles.rs
- src/app.rs
- src/components/revision_files.rs
- src/components/revision_files_popup.rs
- src/tabs/files.rs
> make fetching tree files async

- CHANGELOG.md
- src/strings.rs
> improve help on where to use amend command

- .github/workflows/ci.yml
adding check for unused deps to the CI
> Check udeps

- Cargo.lock
- Cargo.toml
- src/keys/key_list.rs
- src/keys/key_list_file.rs
- src/keys/mod.rs
> Revert "Refactor key_list and remove  key_list_file (#1511)"

- README.md
see https://github.com/extrawurst/gitui/issues/1636
> better binary explanations

- src/components/commit.rs
This Pull Request fixes/closes #1689 
- [ x] I ran `make check` without errors
- [ x] I tested the overall application
> too many things skipped with !verify

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/components/commit.rs
> Fix 1745 commit template problem

- Makefile
- asyncgit/src/revlog.rs
- asyncgit/src/sync/logwalker.rs
- src/components/commitlist.rs
- src/components/utils/logitems.rs
- src/tabs/revlog.rs
- src/tabs/stashlist.rs
> Fix: search in log

- CHANGELOG.md
- src/app.rs
- src/components/commitlist.rs
- src/components/stashmsg.rs
- src/queue.rs
- src/tabs/stashlist.rs
> stash list does not update after drop

- CHANGELOG.md
- Cargo.lock
- Makefile
- asyncgit/Cargo.toml
- asyncgit/src/error.rs
- asyncgit/src/filter_commits.rs
> Parallelize log search

- FAQ.md
I didn't create an issue for this as it's just a one character typo fix. I assume that's fine with you
I didn't follow the checklist:
> Change fassion to fashion in FAQ.md

- src/strings.rs
> fix typo with signing-off commits

- asyncgit/src/sync/hooks.rs
> test that proves hook has access to PATH

- CHANGELOG.md
- src/tabs/stashing.rs
> fix stashing tab empty (closes #1986)

- Cargo.lock
- Cargo.toml
- asyncgit/Cargo.toml
- asyncgit/src/lib.rs
- asyncgit/src/sync/commit_filter.rs
- deny.toml
- git2-hooks/Cargo.toml
- git2-testing/Cargo.toml
- src/keys/key_config.rs
- src/keys/key_list.rs
- src/watcher.rs
- vim_style_key_config.ron
> cargo updates

- CHANGELOG.md
- src/app.rs
- src/ui/style.rs
> allow customizing color of focused title bar

- CHANGELOG.md
- src/tabs/status.rs
> allow pushing to empty repo (closes #1919)

- CHANGELOG.md
- src/popups/branchlist.rs
> allow fetch in both tabs of branch list

- CHANGELOG.md
- asyncgit/src/sync/commit.rs
- src/args.rs
- src/ui/style.rs
> better theme file handling

- src/main.rs
> do not panic if invalid repo

- Cargo.lock
> bump dependency that got yanked

- vim_style_key_config.ron
BTW: My old config with bit flags stopped working after the update to 0.25. This should be listed as a breaking change in the CHANGELOG and release info.
> Remove references to bit flags

- .github/workflows/ci.yml
> update ci to msrv

- src/components/textinput.rs
- src/popups/tag_commit.rs
- src/strings.rs
> fixes tag annotation being broken in 0.25

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- Makefile
> Build apple x86

- CHANGELOG.md
- asyncgit/src/sync/repository.rs
- asyncgit/src/sync/submodules.rs
- asyncgit/src/sync/utils.rs
> supply libgit2 with flag to respect env variables

- src/popups/file_revlog.rs
- src/popups/push.rs
- src/popups/push_tags.rs
```
❯ cargo +nightly version
cargo 1.91.0-nightly (840b83a10 2025-07-30)
❯ cargo +nightly clippy --version
clippy 0.1.90 (0060d5a2a8 2025-08-04)
```
> Fix clippy errors on nightly

- git2-hooks/src/hookspath.rs
This PR fixes clippy issues discovered in this PR: #2717.
> Address clippy issues
