gitui-org/gitui

.gitignore, Cargo.lock, asyncgit/Cargo.toml, asyncgit/src/diff.rs, asyncgit/src/error.rs, asyncgit/src/lib.rs, asyncgit/src/revlog.rs, asyncgit/src/status.rs, asyncgit/src/sync/commits_info.rs, asyncgit/src/sync/diff.rs, asyncgit/src/sync/hooks.rs, asyncgit/src/sync/hunks.rs, asyncgit/src/sync/logwalker.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/reset.rs, asyncgit/src/sync/status.rs, asyncgit/src/sync/tags.rs, asyncgit/src/sync/utils.rs, src/app.rs, src/components/changes.rs, src/components/commit.rs, src/tabs/revlog/mod.rs, src/tabs/status.rs
This pull request tries to replace `unwrap()` calls in asyncgit with error handling via a custom error type defined in `error.rs`. changes has been split into separate commits.
* Added a new error type in `error.rs` file (dependent on `thiserror` crate)
* Added a `Result<T>` type alias for `Result<T,Error>`
* Removed all `unwrap()` calls from `asyncgit` lib except a few in callbacks that I don't know how to deal with for the moment.
I have not touched `unwrap()` inside tests as I am not sure yet if we want to remove them too. I assume they are alright in tests. I will continue to change other files when I get feedback about the code.
=> [WIP] Replace unwrap calls in asyncgit with error handling - closes #53

CHANGELOG.md, Cargo.lock, asyncgit/Cargo.toml, asyncgit/src/sync/hooks.rs
This PR modifies the hook support to enable hook management on windows platform. in order for the code to work on windows I have made sure:
1. we don't try to chmod script files on windows (not needed / not supported)
2. we don't verify if scripts are executable on windows.
3. we use relative path for temp files to prevent path mapping issues for bash on windows.
=> Implement git hook support on windows- closes 14

asyncgit/LICENSE.md, scopetime/LICENSE.md
Those are released separately on crates.io and they do not contain
LICENSE file now that is required when packaging them in Linux
distributions.
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>
=> chore: Add LICENSE file into the sub-crates

README.md
P.S> It will be available only in F32+ and should be pushed there within a few days: https://bodhi.fedoraproject.org/updates/FEDORA-2020-d3770ba5a9
=> README: Add Fedora instructions

README.md
I've created [an AUR package](https://aur.archlinux.org/packages/gitui/) for `gitui`. This PR notes it in the README along with the other platforms/distributions.
=> Note AUR package in README

src/app.rs, src/keys.rs
This PR fixes a small but annoying bug on windows that prevents `SHIFT + TAB` to select the tabs in revers order. The bug is caused by the difference in interpretation of modifiers either in `crossterm` or lower levels. 
for non windows platforms the `SHIFT + TAB` key generates `KeyCode::BackTab` without any modifiers while on windows the same produces `KeyCode::BackTab` + Shift modifier. 
I am not sure the issue should be addressed in `gitui` but here is the fix.
=> fixed an issue with tab reverse on windows.

CHANGELOG.md, asyncgit/src/sync/commit.rs, asyncgit/src/sync/commit_details.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/utils.rs, src/components/commit.rs, src/components/textinput.rs, src/keys.rs, src/strings.rs
=> support commit amend

THEMES.md, src/main.rs
This changes the config directory from the `dirs::cache_dir` to `dirs::config_dir`. It does however keep the cache directory as the default logging directory, as it seems a better fit.
It also adds a function, `migrate_config`, which is called at startup to move directory entries inside the "old" config directory to the "new" one (but it skips moving log files). The intention is that this function can be removed after a few releases when the likelihood of someone upgrading from 0.6.0 or earlier is fairly small.
Fixes #98
=> Move config directory

src/strings.rs
Hi,
first of all, I really like this project.
The 'arrow up' was displayed incorrectly in the 'help command window'. (see: attached screenshot)
Working on a relatively clean Ubuntu 20.04.
=> fix for utf8 encoded arrows in 'help command' window

src/app.rs, src/components/changes.rs, src/components/commit.rs, src/keys.rs, src/main.rs, src/queue.rs, src/strings.rs
This intends to implement a way to enter multi-line commit messages. Ref #46 
This adds support for opening a file in an external editor, writing the commit message and saving it to the file, and the use the entered message as the commit message. This works in much the same way git does by default.
This PR at, in it's current state is not ready for merging. There are a few issues which will need to be resolved first and I hope to get some feedback on how to solve these. They are as follows:
> This is only an issue when the editor is opened inside the terminal (such as _vim_), and not as an external GUI application (such as _VS Code_).
The background thread spawned by gitui will continue to run and capture key strokes while the external editor is in use. I see mainly three ways of solving …
=> Multiline commit message

asyncgit/src/sync/utils.rs
=> allow undefined user.name on commit

.github/workflows/cd.yml
Uses https://github.com/mislav/bump-homebrew-formula-action for updating Homebrew core formula.
=> Add CD action to update Homebrew formula

asyncgit/src/sync/commit_files.rs, asyncgit/src/sync/stash.rs
Stash commits treat untracked files specially in a parent commit of the actual stash commit. this causes the details of the commit to not include these untracked files.
The fix is to treat commit messages differently when showing the details of a commit message. here we detect that the shown commit is actually a commit messages and add any files inside the third parent to the list of files included in the commit. I have also modified the diff function to calculate the diff from the correct commit when calculating the diff on an untracked file inside a stash commit.
=> Stash commit details should include untracked files (fixes #130)

src/app.rs, src/components/commit.rs, src/keys.rs, src/main.rs, src/queue.rs, src/strings.rs, src/tabs/status.rs
Pressing `e` while looking at a file in the _Status_ view will launch an external editor with the current file opened. The editor chosen is determined by the default logic introduced in #114.
An improvement to this in the future could be launching at the specific line at which the _Diff_ view is focused, but that seems to require a change in `FileDiff` which is a change bigger than this PR.
Fixes #166
=> Add command to edit selected file in editor

CHANGELOG.md, asyncgit/src/diff.rs, asyncgit/src/lib.rs, asyncgit/src/revlog.rs, asyncgit/src/sync/commits_info.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/tags.rs, asyncgit/src/tags.rs, src/components/commit_details/details.rs, src/components/commit_details/mod.rs, src/components/commitlist.rs, src/components/inspect_commit.rs, src/tabs/revlog.rs
=> Async tag fetching

asyncgit/src/sync/commit.rs, asyncgit/src/sync/mod.rs, src/app.rs, src/components/mod.rs, src/components/tag_commit.rs, src/keys.rs, src/queue.rs, src/strings.rs, src/tabs/revlog.rs
Opened as a draft for getting early feedback.
Open questions:
to rely on git refusing invalid tags?
Will close #103.
=> Add command for tagging commit

Cargo.lock, Cargo.toml, src/components/externaleditor.rs, src/main.rs
Bumps `dirs` to version 3.0 and add migration logic to move the config files to the new location. The migration only happens on _macOS_, as it's the only OS affected.
This also fixes a bug where file paths with spaces would not open correctly in external editors. As part of the fix, the code for launching the editor switches to using `OsStr` instead of `str` to prevent gitui from messing file paths up should they contain invalid UTF-8.
Fixes #175 
Closes #174
=> Bump `dirs` version and add config migration

src/tabs/status.rs
If the focus is on the working directory and it becomes empty (no files are listed) by either staging the last file or using the _Stage all_ command, the focus will be moved to the stage automatically. It works the same for when the stage becomes empty, by moving the focus to the working directory.
If the focus is on the diff area, the focus will not be moved when either the working directory or the stage becomes empty.
Fixes #215
=> Switch focus when working directory or stage becomes empty

Cargo.lock, Cargo.toml, asyncgit/src/sync/commit_details.rs, asyncgit/src/sync/mod.rs, src/components/commit_details/details.rs, src/components/commit_details/mod.rs, src/components/filetree.rs, src/keys.rs, src/strings.rs
=> Add scrolling to long commit messages

.github/workflows/ci.yml, asyncgit/src/sync/hooks.rs
This PR fixes #235.
The extra newline at the beginning of the hook caused the following error on windows:
`error: cannot spawn .git/hooks/commit-msg: No such file or directory`
=> Adjusted hook tests to work on windows

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/app.rs, src/components/changes.rs, src/components/diff.rs, src/components/inspect_commit.rs, src/components/mod.rs, src/components/utils/mod.rs, src/keys.rs, src/strings.rs, src/tabs/status.rs
This is a first attempt at implementing multiple selection in the diff view.
You can use `Shift+ArrowUp` as well as `Shift+ArrowDown` to extend the
selection.
Known issue: If the selection spans more than one hunk, only the hunk that
contains the selection’s start is selected. I don’t know a good way to address
that. Preventing the selection from spanning more than hunk seems like an
obvious choice, but then, of course, you could only copy lines out of one hunk
at a time.
Still left to do is the actual copying to clipboard, but that should be fairly
easy once the above issue is resolved.
Closes #229.
=> Add multiple selection in diff view

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, Makefile, src/clipboard.rs, src/components/diff.rs, src/main.rs
this reverts the new dependency on clipboard and x11 in turn so that static linux binaries can be build again. 
we need to look into a different solution later.
closes #259
=> revert clipboard feature on linux to fix static linux binary build

src/components/filetree.rs, src/components/utils/filetree.rs, src/components/utils/statustree.rs, src/main.rs
Closes #192.
Folds folders up into their parent if they are the only item it their directory.  For example:
Before:
After:
=> Fold folders up into parent if alone in directory

src/components/utils/filetree.rs, src/components/utils/statustree.rs
Fixes #291
Pressing left now causes the selection to jump to the parent rather than just moving up one.
=> Fix left key in tree broken

asyncgit/src/sync/remotes.rs
I modified `remote_callbacks( )` to return a `Result<RemoteCallbacks<'a>>` with an error in case the `credentials` callback fails, I also matched every occurrence of the `remote_callbacks( )` function to handle the possible scenarios.
An error is now correctly displayed when this occurs.
Linked to [#304](https://github.com/extrawurst/gitui/issues/304)
=> Handled crash when git2 fails to obtain username from URL

CHANGELOG.md, src/components/commit_details/details.rs, src/ui/scrollbar.rs
Closes #308 
Implements drawing a scrollbar when the commit message is too long. Also, I changed the minimum area height for the scrollbar to 4 so that the scrollbar would be drawn in the default terminal window (80x25):
=> Draw scrollbar for long commit messages

assets/vim_style_key_config.ron
fix the uppercase keybindings with shift modifier in vim style example
fix #286
=> Fix vim style key binding example

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, Makefile, src/clipboard.rs, src/components/diff.rs
Use `clip` on Windows, `pbcopy` on MacOX, `xclip` on Linux.
Remove dependency on `clipboard`.
Closes #262.
=> Use helper binary for clipboard access (#262)

asyncgit/src/sync/branch.rs
=> Branching unittests

src/components/select_branch.rs
When the terminal is made too small and the branch list is open, the program would crash.  This fixes that so the program just resizes.
=> Fix crash on small terminal size when branch list is open

src/components/select_branch.rs
Fix #346.
I have used a dynamic size (width=60%, height=25%) and I have kept a minimum size for small screen (original size).
Finally, branch name size is now 30% of popup size.
This is very interesting to work on a rust project like this :smiley:
=> feat: dynamic branch popup size

Cargo.lock, asyncgit/Cargo.toml, asyncgit/src/error.rs, asyncgit/src/push.rs, asyncgit/src/sync/cred.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/remotes.rs, src/components/cred.rs, src/components/mod.rs, src/components/push.rs, src/strings.rs
Fix #344
Finally, I use git2 credential help and I retrieve username/password from :
* git credential manager
* url
* git config
I show username textbox only if I can't retrieve it. I clean credentials after push to avoid keeping it in memory.
=> feat: support https push

CHANGELOG.md, asyncgit/src/sync/branch.rs, asyncgit/src/sync/mod.rs, src/tabs/status.rs
=> visualize outgoing/incoming changes

CHANGELOG.md, Cargo.lock, Cargo.toml, src/main.rs
=> update to dirs-next and remove migration code

src/components/changes.rs, src/tabs/status.rs
This fixes #365.
Still not sure if lookup in `update` function is done correctly:
```rust
self.git_branch_name.lookup().map(Some).unwrap_or(None)
```
Other than that I think everything is okay now :)
=> Add branch name in Status and ChangesComponent cleanup

src/components/cred.rs, src/components/mod.rs, src/components/textinput.rs
fix #361 
I don't know if it is ok for you but I managed this one with an input type :
* TEXTAREA = previous behavior
* TEXT : input on one line
* PASSWORD : input on one line and obfuscated
=> feat: password obfuscation

Cargo.lock, Cargo.toml, THEMES.md, src/ui/style.rs
As serialization support is landed in tui v0.10.0, we can remove the custom type. I also updated `THEME.md` to point to the documentation of the tui type.
Closes #149.
=> Remove ui::style::ColorDef in favor up tui::style::Color

src/components/commit_details/details.rs, src/components/diff.rs, src/ui/scrollbar.rs
=> fix scrollbar

src/components/select_branch.rs
Closes #368 
The scrolling in branch list is now the same as the commit-list and the file-list, in that it scrolls only at the top or the bottom and can change speed.
=> Fix select branch list scrolling

asyncgit/src/revlog.rs
Nightly build is failing because of a clippy error, this fixes it.
=> Fix clippy build error

.github/workflows/cd.yml, .github/workflows/ci.yml
Closes #409 
Adds the ability for Github Actions to cache the build process so it doesn't download or build anything if nothing is changed.
=> Add cache to GithubActions

.github/workflows/ci.yml
Is there any reason we aren't caching this?  This is where rustup, rustc, cargo... is stored which are all downloaded at the start of the CI.
=> Cache ./cargo/bin

src/components/select_branch.rs, src/ui/scrollbar.rs
Fixes #392 
No one seemed to be working on it. Apparently everything was already set up, just had to draw the actual scrollbar.
=> Add scrollbar in branchlist

src/components/push.rs, src/ui/style.rs
Fixes #401 
This makes the push gauge red rather than black because explicit black looks odd on most terminals whereas red looks OK.
=> Use theme for push gauge

asyncgit/src/sync/branch.rs, asyncgit/src/sync/cred.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/remotes.rs, src/components/push.rs
this will pick up the first remote we can find. maybe its a better strategy to fail always when no `origin` is present and we have another way to push to a specific remote, or even pull up a popup when wanting to push and no `origin` is defined to choose the remote to use.
closes #486
=> fix crash when no remote called 'origin' present (#486)

THEMES.md, src/app.rs, src/main.rs, src/ui/style.rs
The argument it takes is files a file relative to the app_config directory, meaning if the (linux) user passes `-t example.ron` to gitui then the theme located at `~/.config/gitui/example.ron` will be used. If `~/.config/gitui/example.ron` doesn't exist then `theme.ron` will be used.
This works by setting environment variable `GITUI_THEME` while processing command line arguments and reading it in function get_theme_file.
=> Allow user to set theme with flag

CHANGELOG.md, asyncgit/src/lib.rs, asyncgit/src/sync/commit.rs, asyncgit/src/sync/mod.rs
Related to #79 and #228.
Beware that the additional tests most likely will fail locally because the local git config interferes with them. This PR is intended for testing whether there are issues on CI.
=> Use get_entry instead of get_str

Cargo.lock
When running cargo audit, it says `parking_lot`, a crate on which some crates in this repo depend,  has a vulnerability in `smallvec`.  To fix, this simply runs cargo update.
The memmap problem is out of our control and so cannot be fixed, but that's already been addressed previously.
=> Run cargo update, fix cargo audit problems

src/components/commit.rs
when adding *amend* this got broken because in that case we want to clear out the msg when it was not confirmed.
closes #530
=> keep uncommitted msg around.

CHANGELOG.md, src/app.rs, src/components/commit.rs, src/components/textinput.rs
=> show branchname in commit mssage box

CHANGELOG.md, asyncgit/src/error.rs, asyncgit/src/sync/branch.rs, asyncgit/src/sync/cred.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/remotes.rs, src/components/push.rs
=> prefer 'origin' as default remote if it exists

CHANGELOG.md, Makefile, asyncgit/src/diff.rs, src/components/diff.rs
=> fix some potentials for errors to bubble up 

assets/vim_style_key_config.ron, src/strings.rs
=> Fix vim default config

asyncgit/src/sync/stash.rs, asyncgit/src/sync/status.rs, src/components/filetree.rs, src/tabs/stashlist.rs, src/ui/style.rs
=> Fix 576 stash apply conflicts

src/app.rs, src/keys.rs, src/main.rs, src/ui/style.rs
giving more diagnostics to the user about what went wrong when a config could not be loaded.
closes #570
=> smarter config loading 

README.md
`gitui` is now part of the Arch Linux official community repository.
https://archlinux.org/packages/community/x86_64/gitui/
=> Update Arch Linux install section of README

assets/vim_style_key_config.ron
The same problem as with uppercase <kbd>E</kbd> for opening editor – <kbd>Shift</kbd> cannot be used as modifier in commit-message editing floating window. Use <kbd>Ctrl</kbd> + <kbd>A</kbd> instead.
=> Fix commit_amend in vim style key config

CHANGELOG.md, src/components/pull.rs
=> Fix 624 pull offline

asyncgit/src/sync/commit_details.rs
`CommitMessage::combine` simply concatenates the `subject` string to the `body`. However, when the `CommigMessage` is created from a previous commit message (e.g., when amending a commit), the subject was in a different line than the rest of the commit message.
So, if your commit message was:
```
Line 1
Line 2
```
Commit amend within gitui will set the commit message to `Line1Line2`.
This PR fixes that by introducing a line break in the `format!` macro.
=> Fix CommitMessage combine wrongly concatenating subject to body

CHANGELOG.md, asyncgit/src/fetch.rs, asyncgit/src/sync/branch/merge_commit.rs, asyncgit/src/sync/branch/merge_ff.rs, asyncgit/src/sync/branch/merge_rebase.rs, asyncgit/src/sync/remotes/mod.rs, asyncgit/src/sync/remotes/tags.rs
=> Fix exit on fetching a branch that has no upstream/remote

KEY_CONFIG.md
With commit #b0b37a8 vim style config path in KEY_CONFIG.md was unchanged
=> Updates vim_style_key_config.ron path

asyncgit/src/error.rs, asyncgit/src/sync/blame.rs, asyncgit/src/sync/mod.rs, src/app.rs, src/components/blame_file.rs, src/keys.rs, src/ui/style.rs, vim_style_key_config.ron
- Set default shortcut to `B` instead of `b` because the latter would
shadow `[b]ranches`.
- Add scrollbar.
- Show resolved commit id in title instead of `HEAD`.
- Make commit id bold if it is the commit id the file is blamed at.
- Don’t run blame on a binary file.
- Add shortcut for inspecting a commit in blame view.
This closes #656.
=> Improve blame view

asyncgit/src/blame.rs, asyncgit/src/lib.rs, src/app.rs, src/components/blame_file.rs
- Rename `self.path` to `self.file_path` in `BlameFileComponent`.
- Take into account that `draw_scrollbar` subtracts the area’s height
before calculating the scrollbar’s position.
The implementation closely mirrors the one in `asyncgit/src/blame.rs`. Let me
know if I understood the async part correctly.
I tested the implementation locally in my `gitui` repository, and I did not
encounter any issues, but I also did not spend a large amount of time on
testing. If you think the implementation looks good, I will test it on a few
more repositories.
This closes #661.
=> Add async wrapper to blame

asyncgit/src/sync/commit_details.rs, asyncgit/src/sync/mod.rs, src/components/commit_details/details.rs
=> Fix 663 msg scroll

src/components/commit.rs
If a commit message template is set with...
git config commit.template /path/to/some/file.txt
...this fills the commit message box (and therefore, later, the external
editor) with the contents of that file, as long as you don't have something
more interesting typed there already.
Like the `git commit` command, this doesn't let you create a commit that has
just the template as its message, unchanged.  Unlike the `git commit` command,
not being able to read the template file is not fatal: specifically, if the
commit.template setting is pointed at a file that does not exist, this does
nothing.
Resolves #546.
=> Load a commit.template message if one is configured (#546)

asyncgit/src/sync/remotes/mod.rs
Currently unit tests require a remote git repository from GitHub. This
change allows unit tests to be run offline. Closes #613
=> Allow unit tests to be run offline

src/ui/style.rs
Screenshots:
See #719 for "before" screenshots and additional context.
=> Remove hardcoded white color from selected tab (#719)

src/ui/style.rs
See #722
I think this makes the most sense, because the yellow color hasn't been a thing since [v0.3.0](https://github.com/extrawurst/gitui/releases/tag/v0.3.0) (that release is a year and a day old today). But if you want that back as the default, I can make that adjustment.
=> Allow overriding selected_tab via theme

asyncgit/src/sync/mod.rs, asyncgit/src/sync/utils.rs, src/components/commit.rs
we now use `.git/COMMIT_EDITMSG` for vim to recognise
closes #518
=> change temporary commit msg file path

CHANGELOG.md, src/components/commit.rs
=> Fix 740 gpgsign warning

CHANGELOG.md, asyncgit/src/status.rs, asyncgit/src/sync/config.rs, asyncgit/src/sync/diff.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/reset.rs, asyncgit/src/sync/status.rs, asyncgit/src/sync/utils.rs, src/components/commit.rs, src/components/externaleditor.rs, src/tabs/stashing.rs, src/tabs/status.rs
=> honor showUntrackedFiles config

CHANGELOG.md, Cargo.lock, Makefile, filetreelist/Cargo.toml, filetreelist/src/filetreeitems.rs
we used a BTreeMap where ordering does not matter and HashMap performs much better
closes #756
=> improve filetree::new performance

CHANGELOG.md, filetreelist/src/error.rs, filetreelist/src/filetree.rs, filetreelist/src/filetreeitems.rs, filetreelist/src/item.rs, src/components/revision_files.rs
=> fix path handling on windows

CHANGELOG.md, src/components/branchlist.rs, src/components/cred.rs, src/components/externaleditor.rs, src/components/pull.rs, src/components/push.rs, src/components/push_tags.rs, src/components/taglist.rs, src/strings.rs
=> popups clear help commands

asyncgit/src/lib.rs, asyncgit/src/remotes.rs, asyncgit/src/sync/remotes/mod.rs, asyncgit/src/sync/remotes/tags.rs, src/app.rs, src/components/taglist.rs
This partly addresses #742.
Let me know whether I put the async code in the right place or whether you’d like it moved to a different location!
=> Show symbol if tag is not yet pushed

asyncgit/src/sync/logwalker.rs
This is the first step towards adding a file history view. The filter itself is not related to files specifically, though. It could also be used for different purposes.
This belongs to #381.
=> Add filter to LogWalker

src/components/taglist.rs, src/strings.rs
This is a small PR that contains minor improvements to the tags popup. I tested it locally, and in my copy of the `gitui`, I encountered no issues.
- Update missing remote tags after tags are pushed.
- Add shortcut for files tab to help.
=> Add push tags to popup

asyncgit/src/revlog.rs, asyncgit/src/sync/logwalker.rs, asyncgit/src/sync/mod.rs, src/tabs/revlog.rs
This is a small change that makes it possible to reuse the logic in `AsyncLog` for the file history view. `AsyncLog` passes the filter to `FileLogWalker` unchanged.
@extrawurst What do you think? Does it make sense to share the revlog logic? An alternative would be to add a `FileRevlog`.
=> Add filter to AsyncLog

CHANGELOG.md, asyncgit/src/sync/remotes/callbacks.rs, asyncgit/src/sync/remotes/mod.rs, asyncgit/src/sync/remotes/push.rs, asyncgit/src/sync/remotes/tags.rs
=> error if force push was rejected

vim_style_key_config.ron
Change `exit` (which exits the app regardless of context) to <kbd>Ctrl</kbd>+<kbd>C</kbd>, and move <kbd>Shift</kbd>+<kbd>Q</kbd> to `quit` (which doesn’t cause quitting on upper-case `Q` insert in popup inputs, cf. #771).
+ make indendation consistent
=> vim style config: allow Q in pop-up inputs

CHANGELOG.md, asyncgit/src/sync/branch/mod.rs, asyncgit/src/sync/mod.rs, src/components/create_branch.rs, src/strings.rs
=> check branch name validity while typing

asyncgit/src/push.rs, asyncgit/src/sync/branch/merge_commit.rs, asyncgit/src/sync/branch/merge_ff.rs, asyncgit/src/sync/branch/merge_rebase.rs, asyncgit/src/sync/branch/mod.rs, asyncgit/src/sync/remotes/push.rs, asyncgit/src/sync/remotes/tags.rs, src/app.rs, src/components/branchlist.rs, src/components/push.rs, src/components/reset.rs, src/queue.rs, src/strings.rs, src/tabs/status.rs
This MR aim to fix #622.
Please comment, and I will do my best to fix what's wrong.
=> ability to delete remote branch

asyncgit/src/sync/branch/mod.rs, src/components/branchlist.rs
Fixes #847.
First contribution here! I'm still getting used to the codebase so please tell me if I overlooked a simpler solution.
Anyways, I choosed the U+2193 (↓) character to represent a remote branch with a tracking branch; it matches with the U+2190 (↑) symbol that represents a local branch with a remote tracking branch. If you find a more fitting symbol for this, I'll gladly change it.
=> Display mark for remote branches with tracking branches

CHANGELOG.md, asyncgit/src/sync/branch/merge_rebase.rs, asyncgit/src/sync/rebase.rs, src/components/branchlist.rs
=> Conflict free rebase

CHANGELOG.md, src/app.rs, src/components/pull.rs
=> make fetch more error resilient 

CHANGELOG.md, src/ui/style.rs
This Pull Request fixes/closes #922.
- Updates the foreground color for selected branch in the branch popup
=> Improve contrast in branch popup for selected branch

asyncgit/src/sync/merge.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/rebase.rs, asyncgit/src/sync/state.rs, src/app.rs, src/components/changes.rs, src/components/commit.rs, src/components/reset.rs, src/keys.rs, src/queue.rs, src/strings.rs, src/tabs/status.rs
=> allow rebase with conflicts (WIP)

CHANGELOG.md, asyncgit/src/lib.rs, src/components/commit.rs
This Pull Request fixes/closes #917.
Adds message cleanup using built-in git_message_prettify function on commit
Changes custom cleanup for git_message_prettify after using external commit message editor
=> Use git_message_prettify

CHANGELOG.md, Cargo.toml, src/components/utils/emoji.rs, src/components/utils/logitems.rs, src/components/utils/mod.rs
gh-emoji crate includes *images* of GitHub's emoji - this is quite big dependency. It increases the binary size by 1 MiB; that's +25 % when building v0.18.0 on Alpine Linux with build flags to optimize size. I consider it an unnecessary bloat that should be optional.
Note: I’m maintainer of Alpine Linux’s [gitui](https://pkgs.alpinelinux.org/packages?name=gitui) package ([APKBUILD](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/gitui/APKBUILD)).
=> Make gh-emoji optional

CHANGELOG.md, asyncgit/src/sync/commit_files.rs
seems to be way faster than using `diff.foreach`
closes #976
=> improve files in diff speed (#976)

CHANGELOG.md, asyncgit/src/sync/blame.rs
=> fixup windows path (#981)

CHANGELOG.md, KEY_CONFIG.md, src/keys/key_config.rs, src/keys/key_list.rs, src/keys/key_list_file.rs, src/keys/mod.rs, vim_style_key_config.ron
=> simplify key bindings file handling

Makefile, asyncgit/src/status.rs, asyncgit/src/sync/status.rs, src/string_utils.rs
=> fix status fetch hanging on bare repos w/o worktree

CHANGELOG.md, README.md, asyncgit/src/sync/commit.rs, src/components/commit.rs
=> keep commit msg on hook-fail

CHANGELOG.md, vim_style_key_config.ron
This Pull Request fixes/closes #1039
- added `gg`/`G` vim bindings to `vim_style_key_config.ron`
=> add gg/G to vim config

CHANGELOG.md, src/components/branchlist.rs, src/tabs/status.rs
This Pull Request fixes/closes #1047
dis able the following buttons and functions in repos without any remote branches
- push in status tab
- pull in status tab
- fetch in branches window of status tab
=> Disable fetch,pull,push on local only repo

README.md, asyncgit/src/sync/commit.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/remotes/tags.rs, asyncgit/src/sync/tags.rs, src/components/commit_details/details.rs, src/components/commitlist.rs, src/components/tag_commit.rs, src/components/textinput.rs, src/keys/key_list.rs, src/keys/key_list_file.rs, src/strings.rs
=> support annotated tags

CHANGELOG.md, README.md, asyncgit/src/sync/cred.rs
=> fix credential.helper usage

CHANGELOG.md, src/components/blame_file.rs
This Pull Request fixes/closes #1117 .
- Transform tabs to spaces in blame file.
=> Fix blame tabs indentation

asyncgit/src/blame.rs, asyncgit/src/diff.rs, asyncgit/src/revlog.rs, asyncgit/src/sync/blame.rs, asyncgit/src/sync/commit_files.rs, asyncgit/src/sync/diff.rs, asyncgit/src/sync/logwalker.rs, src/app.rs, src/components/blame_file.rs, src/components/file_revlog.rs, src/components/revision_files.rs, src/components/status_tree.rs, src/queue.rs, src/strings.rs
=> fix left arrow closing popup

filetreelist/src/filetree.rs, src/app.rs, src/components/blame_file.rs, src/components/branchlist.rs, src/components/changes.rs, src/components/commit_details/mod.rs, src/components/compare_commits.rs, src/components/file_revlog.rs, src/components/inspect_commit.rs, src/components/mod.rs, src/components/revision_files.rs, src/components/revision_files_popup.rs, src/components/status_tree.rs, src/main.rs, src/popup_stack.rs, src/queue.rs, src/tabs/revlog.rs, src/tabs/stashing.rs, src/tabs/stashlist.rs
=> generic popup stacking solution

README.md
gitui can now be installed on android (termux): https://github.com/termux/termux-packages/pull/9076
- README
Signed-off-by: PeroSar <perosar1111@gmail.com>
=> README: Add `Termux (Android)` installation

CHANGELOG.md, asyncgit/src/diff.rs, asyncgit/src/sync/commit_files.rs, asyncgit/src/sync/diff.rs, asyncgit/src/sync/hunks.rs, asyncgit/src/sync/merge.rs, asyncgit/src/sync/patches.rs, asyncgit/src/sync/remotes/push.rs, asyncgit/src/sync/reset.rs, asyncgit/src/sync/staging/stage_tracked.rs, asyncgit/src/sync/status.rs, asyncgit/src/sync/utils.rs, src/components/changes.rs, src/components/compare_commits.rs, src/components/diff.rs, src/components/file_revlog.rs, src/components/inspect_commit.rs, src/components/mod.rs, src/components/status_tree.rs, src/components/utils/filetree.rs, src/components/utils/statustree.rs, src/queue.rs, src/tabs/status.rs
This Pull Request closes #1038.
- Add status change on rename
- Change diff title to represent rename
- Change diff to show only rewrites on rename
=> Change diff renamed files

CHANGELOG.md, src/components/commitlist.rs, src/components/revision_files.rs, src/ui/style.rs
- Selected line in log and files tab now fill the entire container
- Command bar visible commands uses a different background colour than the selection_bg colour
=> Improve UI selection and command bar

Cargo.lock, Cargo.toml, deny.toml, src/app.rs, src/main.rs, src/watcher.rs
=> File watching using notify

CHANGELOG.md, src/components/textinput.rs
- Add common word motions to the text input component, more precisely `Ctrl-Left`, `Ctrl-Right`, `Ctrl-Backspace`/`Ctrl-W` and `Ctrl-Delete`. A word motion move/delete until the next/previous start of a word. A word is being defined as a continuous sequence of alphanumeric characters.
=> Add word motions to text input

CHANGELOG.md, src/components/commit_details/mod.rs, src/components/status_tree.rs
This Pull Request fixes/closes #1122.
- When blaming file from the log tab selected revision is used.
=> file blame at right revision from commit-details

src/main.rs
This Pull Request fixes/closes #1315.
- changes exit code to 1, while initializing gitui in a bare git repo (let me know if the exit code needs to be something else)
=> fix: returns 0 exit code on error

CHANGELOG.md, Cargo.lock, Cargo.toml, asyncgit/Cargo.toml
Please see the commit messages and changelog items.
I’m the maintainer of the [gitui](https://pkgs.alpinelinux.org/packages?name=gitui) package in Alpine Linux. The package is build with Onigurama and system-provided libgit2 (without vendored openssl) since the beginning (more than a year ago), so now I’m just upstreaming these changes.
=> Allow to build without vendored openssl, allow to build syntect with regex-onig

CHANGELOG.md, src/app.rs, src/components/changes.rs, src/components/file_revlog.rs, src/components/mod.rs, src/components/options_popup.rs, src/main.rs, src/options.rs, src/tabs/status.rs
=> persist current tab as options

CHANGELOG.md, src/ui/style.rs
=> selected items should have dedicated fg color

CHANGELOG.md, src/components/commitlist.rs, src/tabs/revlog.rs, src/ui/style.rs
fixes #1252
- adds fg colors to the theme for tags and branches
- displays local branches as labels on their respective commit heads
=> Display tags and branches in the revlog

rust-toolchain.toml
This PR is to add the rust-toolchain file that allows all those who want to contribute or run the project to do it under the same version of Rust
When I did my PR, I did it working under the version of rust that I use in my day to day (a nightly version), which caused confusions and problems when incorporating the changes, I have also seen something similar happen in the PR of [clippy fixes](https://github.com/extrawurst/gitui/pull/1390), so I think it is necessary to be able to work together in a safe and orderly way.
This Pull Request not fixes/closes any
- Add rust-toolchain file
=> Generate rust toolchain file - to develop (and build)

CHANGELOG.md, src/app.rs, src/strings.rs
This Pull Request fixes #1341.
- displays current repository path in the top-right corner
=> Display current repository path in the top-right corner

.cargo/config, .github/workflows/cd.yml, .github/workflows/ci.yml, CHANGELOG.md, Makefile
This Pull Request fixes/closes #1343.
- Adds compilation target for ARM, ARMv7 and AARCH64
As now code was changed, no tests beyond executing the binary are needed.
=> Add Linux targets for ARM, ARMv7 and AARCH64

src/clipboard.rs, src/components/commitlist.rs, src/components/utils/mod.rs, src/strings.rs, src/tabs/revlog.rs
This Pull Request improves failures to copy to clipboard for more system configs.
Right now, when xsel and xclip fail, they return 1 but the status is never checked and execution seems successful.
Additionally, xsel's stderr output sometimes overwrites the screen in random places.
- preamble refactor of commit copying
- reports subprocess failure from `clipboard::exec_copy_with_args`
- opens failure popup without closing the application when copying to clipboard fails
=> Report failure to copy to clipboard

src/components/revision_files.rs, src/components/revision_files_popup.rs
- displays the commit name besides the hash in the file view
=> Display commit description in addition to hash in file view

CHANGELOG.md, src/components/blame_file.rs, src/components/commitlist.rs, src/components/compare_commits.rs, src/components/diff.rs, src/components/file_revlog.rs, src/components/inspect_commit.rs, src/components/mod.rs, src/components/syntax_text.rs, src/components/taglist.rs, src/components/utils/mod.rs, src/components/utils/scroll_horizontal.rs, src/components/utils/scroll_vertical.rs, src/string_utils.rs, src/tabs/status.rs, src/ui/mod.rs, src/ui/reflow.rs, src/ui/scrollbar.rs
This Pull Request fixes/closes #1017.
This is an attempt to finish the work started by @M1cha. It fixes a few minor issues, makes clippy pass and was rebased onto the latest master.
https://github.com/extrawurst/gitui/pull/1327#issuecomment-1328334996
=> Allow to scroll diffs horizontally

CHANGELOG.md, asyncgit/src/sync/hooks.rs
This Pull Request fixes/closes #1528.
- `run_hook` finds git's bash not wsl's on Windows.
- make `cargo test -p asyncgit sync::hooks::tests::test_commit_msg_no_block_but_alter` pass on my machine.
- Add unit tests that run shell commands in hook scripts (test `-l` options).
=> Fix commit hooks error and "no such file" error on Windows with wsl2 installed.

CHANGELOG.md, src/components/commitlist.rs, src/tabs/revlog.rs
sometimes messages appear empty because getting the revlog is so fast (empty repo) that no draw happened yet and so we do not know yet what size the view will have.
fixes #1473
=> fix race issue in revlog message fetching

CHANGELOG.md, src/clipboard.rs
This Pull Request fixes/closes #1497 
- It adds a boolean argument to determine if stderr should be piped, and sets it to false when running the xclip command.
I was able to reproduce the linked issue. If I run `killall xclip` then the UI resumes normal function. This issue started with e371153034db126235f342b52e2e6301e0880e70. Removing the `.stderr(Stdio::piped())` line fixes the freezing, but breaks the error reporting.
`xclip` waits for input on stdin. Something about piping stderr and stdin seems to cause the program to continue waiting for input. I tried different arguments to pass to xclip to tell it to exit, but nothing I tried seemed to work. I tried writing \x03 (End of Text) and \x04 (End of Transmission) and a few others that may have indicated to …
=> Fix freeze on copy when xclip is installed on Linux

CHANGELOG.md, src/clipboard.rs
Hi! I think [my comment here](https://github.com/extrawurst/gitui/pull/1547#issuecomment-1455033008) may have been confusing. There were still some minor code changes required to apply the fix to `wl-copy` as well. Thanks for taking a look!
=> fix freeze on copy with wl-copy

README.md
Since gitui is now available in the official software repository for openSUSE Tumbleweed it would make sense to add it to the install instructions.
- README.md: Add installation instructions for openSUSE Tumbleweed
=> Add openSUSE (TW) to 'Installation' section

src/components/textinput.rs
simple fix in the end. Restores the behaviour - 
which is that 
h.insert("\n", "\u{21b5}\n\r"); // old
h.insert("\n", "\u{21b5}\r\n\n");  // new
this substitution string gets parsed as
`arrow` and `""`
The new one works on stable and nightly
=> fix test failure on nightly due to cef81dc

CHANGELOG.md, asyncgit/src/sync/branch/mod.rs, asyncgit/src/sync/mod.rs, src/components/commitlist.rs, src/tabs/revlog.rs
I opened this draft in order to have the PR run on CI. `make check` passes on 1.68.2, but one tests fails on nightly. The PR itself is mostly done, I think. I’ll add more context to this description in the coming days.
This Pull Request closes #1501.
- Show remote branches in revlog
- Don’t show upstream if commit is local branch head
=> Show remote branches in log

CHANGELOG.md, FAQ.md, src/args.rs, src/main.rs, src/watcher.rs
This Pull Request fixes/closes #1444.
- This commit reintroduces code that was previously removed in favor of a notify-based update trigger. It turned out that notify-based updates can cause issues in larger repositories, so tick-based updates seemed like a safer default.
PR that introduced the notify-based watcher: https://github.com/extrawurst/gitui/pull/1310
=> Default to tick-based updates

src/components/file_revlog.rs
This Pull Request partly fixes #1560.
There is a lot of context in the comment I included in the change. As far as I can tell, this fix works for histories that have <= 1200 entries. If we want a solution that addresses the issue for larger histories as well, we can hopefully take this PR as a starting point. For the time being, I thought it would be best to open the PR in this state already, so we have more context and can start a discussion.
- It brings `self.items.index_offset` always in sync with `self.table_state` by always using `0` as the items’ offset
=> Fix file history for sizes <= 1200 entries

src/input.rs
crossterm 0.26 adds key release event on windows, this causes all key inputs to be duplicated in apps that dont explciitly look at the key event type
- in input.rs is not key press then skip input
- [ x] I ran `make check` without errors
- [ x] I tested the overall application
=> fix double key input on windows due to crossterm 0.26

CHANGELOG.md, THEMES.md, src/main.rs, src/ui/style.rs
This Pull Request closes #1367.
Theme overrides are now loaded the same way key overrides are loaded. The config file, `theme.ron`, does not have to contain a complete theme anymore. Instead, it is possible to specify only the values that are supposed to override their corresponding default values.
This PR is marked as draft because this change is breaking, and their is no automatic migration for existing configs. If that’s ok, I would extend the `Breaking Changes` entry, otherwise I would add code to migrate existing themes.
Update 2023-06-25: I added code for migrating existing themes to the new format.
=> Simplify theme overrides

CHANGELOG.md, src/components/fuzzy_find_popup.rs
Sorry.
When I tried to implement fuzzy_find in other content, I found a bug in fuzzy_find_popup.rs.
Before Fix
After Fix
=> fixed wrong fuzzy-find highlight in long str

CHANGELOG.md, src/components/fuzzy_find_popup.rs
This Pull Request fixes/closes #1732.
- It makes the fuzzy-find popup scrollable
=> Make fuzzy find popup scrollable

CHANGELOG.md, src/keys/key_config.rs
This Pull Request fixes/closes #1751.
- follow symlinks for `key_bindings.ron` and `key_symbols.ron`
=> 1751 follow symlink for keybinding config

Cargo.lock, Cargo.toml, asyncgit/Cargo.toml, deny.toml, src/args.rs
closes #1782 
~~right now blocked because somehow `shellexpand` pins us back to also use `dirs` version 4.x which is weird because its toml allows dirs `>=4, <6`~~
=> switch back to `dirs`

CHANGELOG.md, README.md
This Pull Request fixes/closes #1626.
- added install instructions for anaconda to `README.md`
=> add anaconda install instructions 

CHANGELOG.md, asyncgit/src/sync/branch/mod.rs
Motivated by issue #1399 I added some modifications that should make `checkout_branch` a bit more flexible.
Current implementation depends on `checkout_head` which isn't recommended by [this](https://libgit2.org/libgit2/#HEAD/group/checkout/git_checkout_head). I replaced it with a combination of `checkout_tree` and `set_head` which seems better (as far as my manual testing goes).
Please let me know if this looks okay and if there is anything more needed (e.g. more tests?).
This Pull Request partly fixes #1399.
- `checkout_branch` behaviour
[Here](https://asciinema.org/a/uwiztIHp6k3Nea5beXimGhD3I) is an example of how it works now (changing the branch with a changed file wasn't possible before this change).
=> Modify checkout implementation making branch switching more similar to CLI git behaviour

asyncgit/src/sync/logwalker.rs, src/components/log_search_popup.rs
=> Search commits by author

CHANGELOG.md, src/components/commitlist.rs
This Pull Request resolve the discussion #1665 .
- Copy Commit hash will copy the full hash now instead of the short version of it
=> Copy full Commit Hash by default

Cargo.lock, Cargo.toml, src/components/commitlist.rs, src/components/utils/logitems.rs, src/tabs/revlog.rs
=> Index of search result

.github/workflows/cd.yml, .github/workflows/ci.yml
This Pull Request closes #1844.
- use `actions/checkout@v3`
- switch from `actions-rs/toolchain` (not maintained) to [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain)
- switch from `actions-rs/audit-check` (not maintained) to [`rustsec/audit-check`](https://github.com/rustsec/audit-check)
These changes resolved all the warnings.
Used [`rust-cache`](https://github.com/Swatinem/rust-cache) as mentioned in the issue.
> **Note** 
> `rust-cache`:
> - caches `.cargo/` and `target/`
> - hashes `Cargo.lock` for the key automatically
>
> hence their removal from the ci script 
I kept the `cache-name` around and added a `target` variable as well.
I think the best way to figure that out would be to wait for another commit to be made to master which I can merge to my fork so we …
=> Speedup CI

src/components/file_revlog.rs
This Pull Request is a follow-up to #1648 and related to #1560.
- It uses `offset()`, now exposed by `ratatui`, to keep `items`’ offset in sync with `table_state`’s offset.
=> Fix file history for all sizes

CHANGELOG.md, THEMES.md, src/components/diff.rs, src/main.rs, src/strings.rs, src/ui/style.rs
This Pull Request fixes/closes #1894.
- Add `line_break` to `Theme`.
- Printing a line break will now consult the theme.
=> Allow customizing line break visualization

CHANGELOG.md, src/app.rs, src/components/reset.rs, src/queue.rs, src/strings.rs, src/tabs/status.rs
- Adds confirmation dialog for undo commit in staged changes
Closes https://github.com/extrawurst/gitui/issues/1912
=> Add confirmation dialog for undo commit

CHANGELOG.md, src/components/tag_commit.rs
This Pull Request fixes/closes no existing issue. Do I need to open one? Can I just link this PR in the change log?
- Prevents tagging if `tag.gpgsign` is enabled.
- A replica of what #740 and #741 do for commits.
=> Prevent unsigned tagging

README.md
- Update the installation instructions on openSUSE. In addition to the Tumbleweed, since openSUSE Leap 15.5, gitui is available in the official repository.[^1]
[^1]: <https://build.opensuse.org/package/show/openSUSE:Leap:15.5/gitui>
=> Update the installation instructions on openSUSE

CHANGELOG.md, Cargo.lock, README.md, asyncgit/src/sync/hooks.rs, asyncgit/src/sync/mod.rs, git2-hooks/Cargo.toml, git2-hooks/src/lib.rs, src/components/commit.rs
=> Support prepare commit hook

Cargo.toml
based on: https://kobzol.github.io/rust/cargo/2024/01/23/making-rust-binaries-smaller-by-default.html
=> strip debug symbols in release

CHANGELOG.md, src/app.rs, src/components/blame_file.rs
This Pull Request fixes/closes #745.
- Add syntax highlighting for blame view
=> add syntax highlighting for blame view (#745)

CHANGELOG.md, asyncgit/src/filter_commits.rs, src/tabs/revlog.rs
=> cancel commit search

CHANGELOG.md, git2-hooks/src/lib.rs, src/popups/rename_branch.rs
This Pull Request fixes/closes #2062 .
-  Add branch name validation on renaming
=> feat: add branch name validation on renaming

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md, asyncgit/src/sync/blame.rs, asyncgit/src/sync/config.rs, git2-hooks/src/hookspath.rs, invalidstring/README.md, scopetime/README.md, src/components/changes.rs, src/components/diff.rs, src/components/syntax_text.rs, src/main.rs, src/popups/msg.rs
This Pull Request fixes some minor typos
=> fix: fix typos

CHANGELOG.md, asyncgit/src/sync/commit_details.rs, asyncgit/src/sync/tags.rs, src/components/commitlist.rs, src/main.rs, src/popups/blame_file.rs, src/popups/log_search.rs, src/tabs/revlog.rs, src/ui/scrolllist.rs, src/ui/stateful_paragraph.rs, src/ui/style.rs
This Pull Request fixes/closes [2116](https://github.com/extrawurst/gitui/issues/2116)
- Clippy now emits the missing_const_for_fn warning
- `const` has been applied in applicable functions
=> Remove unused clippy warning suppression (missing_const_for_fn)

src/popups/blame_file.rs
This Pull Request fixes/closes #2130.
- Fix index out-of-bound error when blaming a file ending with a blank line
**More details**:
The highlighting procedure works on a single line. It called `str::lines` to split the code into lines. The `str::lines` used `split_inclusive` internally, which omits the ending blank line (https://github.com/rust-lang/rust/issues/111457). So, to overcome that, I added a blank line to the unstyled blame text.
=> fix: index out of bounds when blaming a file ending with a blank line

src/components/textinput.rs, src/components/utils/filetree.rs, src/components/utils/statustree.rs, src/popups/blame_file.rs, src/ui/reflow.rs
This Pull Request fixes/closes #2142.
rustc 1.77 made changes to clippy that makes cargo clippy fail on master branch, this pull request fixes the errors.
- Ran cargo clippy --fix
- Ran cargo fmt
=> Cargo Clippy Errors Fixed

src/popups/inspect_commit.rs
This Pull Request fixes/closes #2114.
The changes done are just reverting the deleted lines from https://github.com/extrawurst/gitui/commit/7dcf93e0b279a7f09a98b44fee88430afa09e149.
There was an idea to open a file at revision using a temp file. Let's discuss it further so I can add it to this PR.
- new event processed (open_file_tree) in InspectCommitPopup (while inspecting a commit)
=> fix: 2114. Going to Files from Details -> Inspect or Diff is not working

asyncgit/src/sync/commit.rs, asyncgit/src/sync/mod.rs, src/popups/commit.rs
This Pull Request fixes/closes #2136.
- Commits will now follow the git config `core.commentChar` if one is not set it defaults to `#`
Screenshot Evidence
=> Git Config Commit Comments

CHANGELOG.md, src/popups/msg.rs
This Pull Request fixes/closes #1138.
- Adds scrolling for tag annotations by adding scrolling to MsgPopups which are used to display tag annotations.
=> Make MsgPopup scrollable

asyncgit/src/sync/commit.rs
This Pull Request fixes/closes #{issue_num}.
- asyncgit/src/sync/commit.rs
=> Fix typo in commit.rs

asyncgit/src/sync/commit.rs
This Pull Request adds tests for the git comment char
It adds the following:
- Tests for checking the commit_message_prettify in commit.rs under async/sync
=> Comment char tests

CHANGELOG.md, Cargo.lock, Cargo.toml, src/ui/syntax_text.rs
This Pull Request fixes/closes https://github.com/extrawurst/gitui/issues/2005.
- add two-face as dependency to extend syntect supported file types
- add two-face feature flags alongside syntect feature flags
- change default SYNTAX_SET to two_face's default (still no newlines)
- [] I added unittests (not needed)
=> syntect additional file type support

CHANGELOG.md, Cargo.lock, asyncgit/Cargo.toml, asyncgit/src/sync/commit.rs, asyncgit/src/sync/sign.rs, deny.toml
This Pull Request fixes #1149 #2173 
ref: #2047 #2023
- A disk ssh key path in `user.signingKey` of gitconfig  will be used to sign the commit 
=> sign with ssh key in disk

Cargo.lock, asyncgit/Cargo.toml, asyncgit/src/error.rs, asyncgit/src/revlog.rs, asyncgit/src/sync/logwalker.rs, asyncgit/src/sync/mod.rs
This PR is split from #2269. It is focuces on the single use case of walking the log when there is no filter.
The current `LogWalker` implementation accepts a `filter` of type `Option<SharedCommitFilterFn>` with `type SharedCommitFilterFn = Arc<Box<dyn Fn(&Repository, &CommitId) -> Result<bool> + Send + Sync>`. As you can see, this function takes a `git2::Repository` as an option. Unfortunately, this does not work with `gix`.
When using `gitx` to walk the log, we open the repository through `gix::open` which returns a `gix::Repository`, a struct that is incompatible with `git2::Repository`. In order to make filtering work with `gix`, we would have to rewrite quite a bit of code in `commit_filter`. In particular, we would have to make `get_commit_diff` work with `gix::Repository`.
In order …
=> Add LogWalkerWithoutFilter, using gitoxide

CHANGELOG.md, git2-hooks/src/hookspath.rs
This Pull Request fixes/closes #2317.
- Add `find_default_unix_shell()`.
- Use default shell instead of bash on Unix-like OS.
Why we need it? macOS uses zsh by default now.
=> Use default shell instead of bash on Unix-like OS

asyncgit/src/error.rs, asyncgit/src/revlog.rs, asyncgit/src/sync/logwalker.rs, asyncgit/src/sync/mod.rs
When opened in a sub-directory of a git repository, the log view crashes. Replacing `gix::open` by `gix::discover` fixes this issue. `gix::open` errors when the passed directory is not a git repository, `gix::discover` searches parent directories for a git repository. The code causing the crash has not been released yet, so no changelog entry is necessary.
=> Fix log crashing in subdirectories

filetreelist/Cargo.toml
This reduces download size for the crate from ~900 kB to ~10 kB.
I didn't file an issue because that feels redundant for the single-line metadata change proposed here (and most of the checklist in the PR template doesn't apply either).
=> filetreelist: exclude demo.gif from published crates

CHANGELOG.md, git2-hooks/src/hookspath.rs
This Pull Request makes changes to accommodate GUI functionality in GitButler (see: https://github.com/gitbutlerapp/gitbutler/issues/4982).
- Set the `CREATE_NO_WINDOW` flag when executing Git hooks on Windows.
=> Set `CREATE_NO_WINDOW` flag when executing Git hooks

asyncgit/src/revlog.rs
This is a follow-up to #2301. It adds a test for `AsyncLog::fetch_helper_without_filter` respecting `GIT_DIR`. The docs to `std::env::set_var` say that it is only safe to be used in single-threaded programs. Could this ever become an issue? On my machine, `make check` was green.
(Creating snapshot tests running the `gitui` binary has proven to be rather challenging. So far, I have not found a crate that would work with `enable_raw_mode` which is why I decided to open this PR.)
=> Add test for AsyncLog respecting GIT_DIR

Cargo.lock, Cargo.toml, src/keys/key_list.rs, src/ui/style.rs
=> Bump struct-patch from 0.4.1 to 0.8.6

asyncgit/src/revlog.rs
This is a follow-up to #2387. It changes the original PR in the following way:
- It marks another test in the same file as `#[serial]`.
- It unwraps `result` in both tests to get more information in case either test fails on CI.
=> Improve test for env variables

CHANGELOG.md, src/clipboard.rs
This PR adds support for the "Copy Path" operation in the "Files" tab when running in WSL.
For those like myself who are accessing WSL from a terminal, there is no X server, so `xclip` won't work. However, my Ubuntu WSL image at work still has `xclip` installed, which `gitui` detects and uses, causing `gitui` to freeze. I have to kill `gitui` at that point.
This PR checks if we are running in WSL by examining the description of the kernel in the OS release file, `/proc/sys/kernel/osrelease`. If `gitui` is running in WSL, we copy the path to the Windows clipboard using the `clip.exe` utility.
=> Support "Copy Path" operation in WSL

Cargo.lock, asyncgit/Cargo.toml, asyncgit/src/sync/logwalker.rs
This is a replacement for #2402 because I don’t have permission to push to that PR. You can also cherry-pick my commit into the Dependabot PR (it’s a very small change).
=> Bump gix from 0.66.0 to 0.67.0 and adapt to API changes

CHANGELOG.md, src/popups/commit.rs
This Pull Request fixes/closes #2476.
-  src/popups/commit.rs
=> fix: File selector should jump back and highlight unstaged files

THEMES.md
tui-rs is unmaintained and gitui has been using ratatui for a long time now (904885e001bddd3c2b36311d69debbc26c3623ca)
=> Update valid colors link in THEMES.md to ratatui

CHANGELOG.md, src/ui/syntax_text.rs
Currently, gitui prioritizes file extensions for syntax detection. When a file lacks an extension (e.g. `Makefile`), or the extension isn't tied to a specific format (e.g. `.lock`), it disables syntax highlighting.
This PR changes the syntax detecton method to the entire filename and the first line of the file using [`find_syntax_for_file()`](https://docs.rs/syntect/5.2.0/syntect/parsing/struct.SyntaxSet.html#method.find_syntax_for_file).
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
<details>
=> Improve syntax detection

src/ui/syntax_text.rs
The previously used function could only take `&str` as its argument, and I blindly copied it over here. This should've been part of #2524, sorry.
=> Remove redundant `to_str()` conversion

deny.toml
cargo deny reports:
```
ID: RUSTSEC-2024-0436
Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0436
The creator of the crate `paste` has stated in the [`README.md`](https://github.com/dtolnay/paste/blob/master/README.md)
that this project is not longer maintained as well as archived the repository
Announcement: https://github.com/dtolnay/paste
Solution: No safe upgrade is available!
paste v1.0.15
└── ratatui v0.29.0
├── gitui v0.27.0
└── tui-textarea v0.7.0
└── gitui v0.27.0 (*)
```
In https://github.com/gitui-org/gitui/issues/2554 the decision was made to ignore this advisory, as ratatui already has removed paste in https://github.com/ratatui/ratatui/pull/1713 and we are just waiting for an upstream release.
This Pull Request is related to #2554, but does not close it until ratatui …
=> Ignore RUSTSEC-2024-0436

CHANGELOG.md, Cargo.lock, Cargo.toml, src/clipboard.rs
This Pull Request closes #2366.
- If copying using wl-clip or xclip and xsel fails, copy using [OSC52](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands) (Search for "Ps = 5 2").
This does not change the default behavior. On both wayland and X, wl-copy and xclip/xsel will be preferred. Only if one path fails, an OSC52 escape sequence will be issued.
I have tested this by running tmux, which has the option to turn support for this off and on (using `:set -g set-clipboard off` or `:set -g set-clipboard on`) and SSH. When tmux's clipboard support was off, no text was copied. Once I enabled it, copying worked as expected. From this I conclude that the whole setup works as expected.
N.B.: There is no easy path for gitui itself to …
=> Copy text using OSC52

CHANGELOG.md, src/args.rs
Add a command-line option to override the default log file path.
`gitui --logging` stays unchanged;
`gitui --logfile path/to/file.log` logs to `path/to/file.log`;
`gitui --logging --logfile path/to/file.log` is equivalent to using just `--logfile`.
This Pull Request fixes/closes #2528.
=> Add `--logfile`

CHANGELOG.md, src/popups/msg.rs
This Pull Request fixes/closes #2552.
- The default key to close the commit error message popup is now the Escape key
=> Dismiss commit msg key

CHANGELOG.md, asyncgit/src/error.rs, asyncgit/src/sync/branch/mod.rs, asyncgit/src/sync/config.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/remotes/push.rs
Fixes #2537
git2 merged [necessary PR](https://github.com/rust-lang/git2-rs/pull/1131)
This PR _is_blocked_ until new version git2 lib released
For now use git2 from master to be able to test PR.
---
Assume git config:
```git-config
[branch "oblava"]
remote = origin
merge = refs/heads/master
[push]
default = upstream
```
Prev. behavior:
push -> push oblava -> remote oblava <- new remote created
New behavior:
push -> push oblava -> remote master
---
=> Push with refspec

CHANGELOG.md, Cargo.lock, Cargo.toml, src/args.rs, src/keys/key_config.rs, src/ui/syntax_text.rs
This Pull Request fixes/closes #2523 & closes #2308.
Custom syntax highlighting themes can be loaded from a `.tmTheme` file.
If `syntax` in `theme.ron` (added in #2532) is a filename that exists in the gitui config directory, it's used as the syntax theme. If not, gitui falls back to selecting from the default theme set.
---
For example, if you put the following in `theme.ron`:
```
(
syntax: Some("mytheme"),
)
```
gitui will load `~/.config/gitui/mytheme.tmTheme`.
---
`make check` reports a duplicate dependency error:
```
error[duplicate]: found 2 duplicate entries for crate 'base64'
```
=> Support loading custom syntax themes from a file

CHANGELOG.md, Makefile
This is run in CI, so running this offline avoids an unnecessary CI failure.
This Pull Request fixes/closes #{issue_num}.
- Adds a `make sort` target, which runs `cargo sort`
- Runs `make sort` also for `make check`
=> Check cargo sort in `make check`

CHANGELOG.md, THEMES.md, src/ui/style.rs
When set to `False` (default `True`), keep the foreground color of the selected object (commit hash, date, etc ...).
It changes the following:  
- Added a new `use_selection_fg` flag to the `Theme` struct, allowing users to toggle whether the selection foreground color is applied.  
- Set `use_selection_fg` to `true` by default in `Theme::Default`.  
- Extended unit tests to validate the behavior of `use_selection_fg`.  
=> feat(ui): Add use_selection_fg flag to control selection foreground color

THEMES.md
This pull request consolidates #2570, #2214, #2564 (via #2573) into a single pull. The result from just merging seemed random, this adds a bit more structure to the document.
- Add to THEME.md:
- Custom syntax highlighting
- Using default syntect themes (picked form #2570)
- Using custom TextMate themes (for #2573)
- Reference themes (picked from #2214)
- Enables syntax highlighting for RON data in THEME.md
- ~~I added unittests~~
- ~~I ran `make check` without errors~~
- ~~I tested the overall application~~
- ~~I added an appropriate item to the changelog~~
=> Consolidate recent theme change docs in THEMES.md

CHANGELOG.md, asyncgit/src/sync/commits_info.rs, src/components/commitlist.rs, src/queue.rs
The algorithm for computing marked_consecutive assumes that commits are consecutive in the commit graph if they are consecutive in the linearized log used in` commitlist.rs`. That is not universally correct, as siblings may also be displayed consecutively in this list.
For now, this just removes generating commit lists in dotted range notation.
This Pull Request fixes/closes #2576 
- Removes dotted range notation commit yanking
=> Disable dotted range commit yanking

CHANGELOG.md, asyncgit/src/sync/hooks.rs, git2-hooks/src/hookspath.rs
git supports a relative path in core.hooksPath.
`man git-config`:
> A relative path is taken as relative to the directory where the hooks are
> run (see the "DESCRIPTION" section of githooks[5]).
`man githooks`:
> Before Git invokes a hook, it changes its working directory to either
> $GIT_DIR in a bare repository or the root of the working tree in a >
> non-bare repository.
I.e. relative paths in core.hooksPath in non-bare repositories are always relative to GIT_WORK_TREE.
There is a further exception; I believe this is not considered for path resolution:
> An exception are hooks triggered during a push (pre-receive, update,
> post-receive, post-update, push-to-checkout) which are always executed
> in $GIT_DIR.
This Pull Request fixes/closes #2281.
- …
=> Resolve core.hooksPath relative to GIT_WORK_TREE

.github/workflows/ci.yml
This Pull Request fixes/closes #315 .
- CI script has a new job that build gitui from source at head, using brew, and runs brew test
- [no] I added unittests
- [no] I ran `make check` without errors
- [no] I tested the overall application
- [no] I added an appropriate item to the changelog
..but, I did make a custom tap of brew, introduced an error in the source code on my fork and let my custom brew discover it. 
The thing is, there is no change to the source code of gitui, only to the CI script. The change looks at gitui main branch head, which I cannot touch - so I had to hack around to fake a test. I have demonstrated that it works on my fork, but not that it works on gitui master branch.
=> Fix #315 run brew test in CI

Cargo.lock, Cargo.toml, asyncgit/Cargo.toml
seems we have to wait for `shellexpand` to upgrade dirs if we do not want dupes: https://gitlab.com/ijackson/rust-shellexpand
=> upgrade dirs

Cargo.lock, git2-hooks/Cargo.toml, git2-hooks/src/hookspath.rs
This deals with one half of #2611
-
-
=> use gix_path::env::shell() to get the shell in git2-hooks

asyncgit/src/error.rs, asyncgit/src/sync/config.rs, asyncgit/src/sync/logwalker.rs, asyncgit/src/sync/patches.rs, asyncgit/src/sync/staging/mod.rs, filetreelist/src/error.rs, filetreelist/src/filetreeitems.rs, src/components/utils/emoji.rs, src/components/utils/logitems.rs, src/options.rs
- Removes a few outdated or easy to fix `#[allow]`s
- ~~I added an appropriate item to the changelog~~
=> Clean up a few `#[allow]`s

src/args.rs, src/components/commit_details/compare_details.rs, src/components/commit_details/details.rs
- Remove unneeded `#[allow]`s, `rg '#.*allow' | wc -l` from 28 to 26.
- ~~I added unittests~~
- ~~I added an appropriate item to the changelog~~
=> Remove some `#[allow]`s II

src/main.rs
ratatui::Terminal starts by hiding the cursor. If we panic and abort, that Terminal instance is not dropped, which leaves restoring the cursor state to us.
- Shows the terminal cursor if gitui panics
- ~~I added unittests~~
- ~~I added an appropriate item to the changelog~~
- left out intentionally for such a minor item
=> Show cursor on panic

CHANGELOG.md, src/main.rs
This Pull Request fixes/closes #2599.
- Improve error messages when the repository cannot be opened.
- for example, when the repo doesn't exist:
```sh
$ gitui
invalid path
please run gitui inside of a non-bare git repository
$ gitui
Error: could not find repository at '.'; class=Repository (6); code=NotFound (-3)
```
- Remove the panic handler from rayon, since `panic::set_hook` already handles all panics. Setting both panic handlers causes the panic message to be displayed twice.
- Do both `log::error!` and `eprintln!` wherever possible
- ~~I get some errors in `Cargo.toml`, but it hasn't been changed in this PR:~~ (see https://github.com/gitui-org/gitui/pull/2617#issuecomment-2810329134)
```
error: Dependencies for . are not sorted …
```
=> Improve error messages

Cargo.lock
This makes `cargo deny check` pass on my machine.
=> Update scc and sdd to non-yanked versions

filetreelist/src/filetree.rs
This is a potential follow-up to #2496.
- It adds `get_new_selection` as the single function that iterates over the list’s items to get the next selection based on a range and a step size.
- It adds `enum Direction` as a more explicit alternative to `up: bool`.
- It removes some loops in favor of iterators and their APIs.
- It removes some duplication with respect to whether the new index is different than the current one.
The only thing I’m worried about is that the ranges passed as arguments to `get_new_selection` potentially are too clever or unintuitive. If you think that’s an argument against this PR as a whole, feel free to close it! :smile: I still wanted to open it in order to get your feedback.
=> Simplify (hopefully) code for moving selection in `filetreelist`

asyncgit/Cargo.toml, scopetime/Cargo.toml
This PR is supposed to fix the lint step on CI.
=> Have cargo-sort 2.0.1 sort Cargo.toml's

Cargo.lock, asyncgit/Cargo.toml, asyncgit/src/error.rs, asyncgit/src/sync/commits_info.rs, asyncgit/src/sync/logwalker.rs
This is related to #2643. I have not been able to figure out why #2643 sometimes fails on CI, but in a way that I have not been able to reproduce locally. So I thought I’d split out the parts that are not related to the CI failures to maybe get them merged earlier. While the initial PR converted both `get_commits_info` (plural) and `get_commit_info` (singular) to `gitoxide`, this PR only converts `get_commit_info`. Apart from that, it is the same as #2643.
=> Use `gitoxide` in `get_commit_info`

Cargo.lock, asyncgit/Cargo.toml, asyncgit/src/error.rs, asyncgit/src/revlog.rs, asyncgit/src/sync/commits_info.rs, asyncgit/src/sync/config.rs, asyncgit/src/sync/logwalker.rs, asyncgit/src/sync/mod.rs, asyncgit/src/sync/repository.rs, asyncgit/src/sync/status.rs, asyncgit/src/sync/utils.rs
I’ve been using this branch daily for the last week. I found one issue that I’ve addressed in a separate commit. I think it’s now ready for review!
This is a draft PR. I think that, at this point, most of the initial work of porting is done. I’m going to be using this branch as my daily driver throughout the week to find any issues there might still be left. I’m planning on marking it as ready for review at the end of the week.
This PR changes `asyncgit::sync::get_status` to use `gitoxide`. As a side-effect, it lets `gitoxide` handle reading `status.showUntrackedFiles`. The resulting behaviour, with respect to `status.showUntrackedFiles`, is closer to what git does than it was before this PR. I’ve updated 2 tests according to the new behaviour.
=> Use `gitoxide` in `get_status`

asyncgit/src/error.rs, asyncgit/src/sync/commits_info.rs, asyncgit/src/sync/tags.rs
This PR is a draft, currently intended for a discussion with @Byron about the part of the API to be used for getting a reference’s name. I intend to mark it as ready once I’ve figured out how to best use the existing APIs.
Update 2025-06-09: this PR is now ready for review.
This PR changes the following:
- It converts `get_tags` to use `gitoxide` under the hood.
- It seems the current implementation might have a bug. At least, the `gitoxide` version properly show an `@` symbol in the tags popup for annotated tags, something the `libgit` version doesn’t do. (I didn’t investigate this in depth, though.)
=> Use `gitoxide` for `get_tags`

src/args.rs
This Pull Request closes #2683.
It changes the error message when the config and/or HOME directory is not writable from:
```
Error: Permission denied (os error 13)
```
to
```
Error: failed to write config to /home/sobczal/Dev/playground/test/.config/gitui
Caused by:
Permission denied (os error 13)
```
=> Improve error message on config dir error
